### ISSUE TITLE
refactor CI to use micromamba

### ISSUE THREAD

**Issue by prjemian** [prjemian/punx#208]
As seen with [apstools](https://github.com/BCDA-APS/apstools/issues/659), it's faster to solve the package requirements and much easier to configure and use:

From the [CI](https://github.com/BCDA-APS/apstools/blob/a47c730c7f89ecc751313d366290af64d6123a37/.github/workflows/unit-tests-pytest.yml#L25-L39) configuration:
```yml
    - name: Create Python ${{ matrix.python-version }} environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yml
        environment-name: anaconda-test-env-py-${{ matrix.python-version }}


    - name: Initial diagnostics
      shell: bash -l {0}
      run: |
        micromamba info
        micromamba list
        conda config --show-sources
        conda config --show
        micromamba env list
        printenv | sort
```
